# Nome da aplicação
spring.application.name=LojaCarro-Test

# Configuração do banco de teste
spring.datasource.url=jdbc:mysql://localhost:3306/lojacarros_test
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jakarta.persistence.validation.mode=auto
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Garante que o data.sql seja executado
spring.sql.init.mode=always
spring.sql.init.platform=mysql
